minimumPay: 0.01 #minimumPay is the lowest amount user's can pay others with the /pay command
offlinePayments: true #Dictates whether players can pay others that are offline with the /pay command
maxBaltop: 5 #Amount of people you want to show up on Baltop