name: SaulConomy
version: ${project.version}
main: me.mazenz.saulconomy.SaulConomy
api-version: 1.16
authors: [ GKasparov ]
description: Economy Plugin
commands:
  balance:
    description: Shows user's balance
    aliases: ['bal']
  setbalance:
    description: Set balance
    aliases: ['setbal', 'setmoney']
  pay:
    description: Pay someone
  saul:
    description: Saul Admin commands
permissions:
  saul.*:
    description: SaulConomy master permissions
    children:
      saul.setbalance: true
    default: op
  saul.setbalance:
    description: Allows user to set others' balances
    default: op
  saul.reload:
    description: Reloads the plugin's configurations
    default: op
