name: SaulConomy
version: ${project.version}
main: me.mazenz.saulconomy.SaulConomy
api-version: 1.16
authors: [ GKasparov ]
description: Economy Plugin
commands:
  balance:
    description: Shows user's balance
    aliases:




