name: SaulConomy
version: 0.1
main: me.mazenz.saulconomy.SaulConomy
api-version: 1.16
authors: [ GKasparov ]
description: Economy Plugin
commands:
  balance:
    description: Shows user's balance
    aliases: ['bal']
  setbalance:
    description: Set balance
    aliases: ['setbal', 'setmoney']
  pay:
    description: Pay someone
  saul:
    description: View all SaulConomy commands
    aliases: ['saulconomy']
permissions:
  saul.*:
    description: SaulConomy master permissions
    children:
      saul.setbalance: true
    default: op
  saul.setbalance:
    description: Allows user to set others' balances
    default: op
